apiVersion: apps/v1
kind: Deployment
metadata:
  name: zio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: zio-app
          image: juliobetta/zio-sample-app:latest
          ports:
            - containerPort: 8090
