apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zio-app.fullname" . }}
  labels:
    {{- include "zio-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zio-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zio-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "zio-app.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            {{- toYaml .Values.healthCheck.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthCheck.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/src/main
              name: {{ include "zio-app.name" . }}-volume
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: {{ include "zio-app.name" . }}-secret
      # learning purposes only...
      volumes:
        - name: {{ include "zio-app.name" . }}-volume
          configMap:
            name: {{ include "zio-app.name" . }}-config
            items:
              - key: application.conf
                path: resources/application.conf
              - key: database.conf
                path: resources/database.conf
