apiVersion: v1
kind: Service
metadata:
  name: {{ include "zio-app.fullname" . }}
spec:
  # it generates an external IP
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      # this name is a requirement for Istio
      name: http-svc
      port: {{ .Values.service.port }}
  # determines which pods will accessible via this service
  # it has to match the selected configured into the deployment file
  selector:
    {{- include "zio-app.selectorLabels" . | nindent 4 }}
