apiVersion: v1
kind: ConfigMap
metadata:
  name: zio-app-config
data:
  # override default configuration if necessary (learning purposes only)
  application.conf: |
    {
      api: { include "api.conf" },
      db: { include "database.conf" }
    }
  database.conf: |
    {
      port: 5432
    }
