apiVersion: apps/v1
kind: Deployment
metadata:
  name: zio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: zio-app
          image: juliobetta/zio-sample-project:0.1.0
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.6"
          volumeMounts:
            - mountPath: /app/src/main
              name: zio-app-volume
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: zio-app-secret
      # learning purposes only...
      volumes:
        - name: zio-app-volume
          configMap:
            name: zio-app-config
            items:
              - key: application.conf
                path: resources/application.conf
              - key: database.conf
                path: resources/database.conf
