apiVersion: v1
kind: Service
metadata:
  name: zio-app-service
spec:
  # it generates an external IP
  type: ClusterIP
  ports:
    - protocol: TCP
      # this name is a requirement for Istio
      name: http-svc
      port: 9000
  # determines which pods will accessible via this service
  # it has to match the selected configured into the deployment file
  selector:
    app: server
